## YAML Template.
---
:root: "Chat::Rooms"
:layout: "Chat::Layout"
:app:
  :name: "Chat"
  :shared: "Chat::Shared"
#:websocket:
#  :server: 192.168.15.100
#  :host: 0.0.0.0
#  :port: 3006
#:web:
#  :host: 0.0.0.0
#  :port: 3005